apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amitha-app
  template:
    metadata:
      labels:
        app: amitha-app
    spec:
      containers:
      - name: blue-app
        image: gcr.io/<your-project-id>/blue-app:v1
        ports:
        - containerPort: 3000
