apiVersion: v1
kind: Service
metadata:
  name: amitha-service
spec:
  selector:
    app: amitha-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
